<div style="text-align: center;">
    <img src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg" alt="Numpy Logo" width="500">
    <p style="font-size: 50px; font-weight: bold;">Pengenalan NumPy pada Python</p>
    <p style="font-size: 50px; font-weight: normal;"> Intern BCC 2026</p>
</div>

# NumPy 🧮

### 🎯 Tujuan Notebook Ini
Setelah selesai, (minimal) bisa:
- memahami struktur data utama (NumPy) dan kapan dipakai
- menulis kode yang rapi untuk kebutuhan data science dasar (cleaning, transform, ringkas data)
- tahu *pitfall* yang sering bikin bingung (dtype, indexing, missing values, dsb.)

**NumPy** atau **Numerical Python** adalah sebuah library Python yang menyediakan struktur data dan fungsi-fungsi untuk bekerja dengan array dan matriks multidimensi untuk kebutuhan **scientific computing menggunakan Python**.

**NumPy** meningkatkan efisiensi dalam melakukan operasi dan manipulasi data dengan ukuran yang besar.

### Install Numpy Package/Module

In [162]:
# Kalau kamu menggunakan Google Colab atau Kaggle Notebook, umumnya package numpy sudah pre-installed.
# !pip install numpy

# if you want to install specific version, you can also do this
# !pip install numpy==2.2.3

### Catatan versi NumPy 
NumPy versi baru (2.x) membawa beberapa perubahan internal. Untuk workshop ini, kamu cukup fokus ke konsep dasar array + operasi NumPy, kodenya tetap mirip.

Untuk menggunakan numpy, kita harus import `numpy` package terlebih dahulu:

### Import Numpy

In [163]:
import numpy as np # 'np' merupakan alias untuk package numpy paling umum

### Array

Seperti list pada python, array merupakan variabel yang memiliki lebih dari 1 anggota. Pada numpy array dapat berbentuk lebih dari 1 dimensi atau sering juga disebut dengan N-dimensional array (*ndarray*).

| Feature       | Python List                                     | NumPy Array                                         |
|--------------|---------------------------------|------------------------------------|
| Storage      | Dynamic type                                   | Fixed type                                           |
| Functionality | General-purpose                              | Mathematical and scientific operations              |
| Speed        | Slower due to type-checking and overhead      | Faster due to vectorized operations and no type-checking |
| Memory       | More due to overhead                         | Optimized and efficient storage                     |

| Feature         | Python Array                                                                                     |
|---------------|--------------------------------------------------------------------------------------------------|
| **Performance**   | Faster than lists for numerical operations, but not as fast as NumPy arrays.                     |
| **Homogeneity**   | Arrays are homogeneous, meaning all elements must be of the same data type.                     |
| **Multidimensional** | Does not natively support multidimensional arrays. Supports nested arrays.                      |
| **Operations**    | The array module supports basic operations such as addition and multiplication, but these operations must be done manually using loops or comprehensions. |
| **Functionality** | Limited compared to NumPy. Mainly used for storing homogeneous data efficiently.                |
| **Memory Usage**  | The array module provides a compact way to store homogeneous data types, such as integers and floats, using less memory than a Python list. However, it does not provide the same level of memory optimization as NumPy. |
| **Indexing**      | Supports basic indexing and slicing.                                                            |
| **Module**        | Array is not a built-in data type in Python. So, in order to use it, import the array module for arrays in Python. |

Reference:
https://www.geeksforgeeks.org/python-lists-vs-numpy-arrays/

Dokumentasi resmi NumPy (pemula):
- https://numpy.org/doc/stable/user/absolute_beginners.html


### `Numpy` Array

Kita dapat menginisialisasi array numpy dengan nested list Python dan mengakses element menggunaan tanda kurung kotak `[ ]`

In [178]:
arr = np.array([1, 2, 3])

print(type(arr))
print(arr.shape, arr[0], arr[1], arr[2])

arr[0] = 5
print(arr)

<class 'numpy.ndarray'>
(3,) 1 2 3
[5 2 3]


## 1D, 2D, 3D Array itu maksudnya apa?

![Numpy Logo](https://www.w3resource.com/w3r_images/numpy-1d2d3d-array.png)

Cara paling gampang: **lihat `shape`-nya**.

- **1D** → seperti “garis” (vektor), bentuknya `(n,)`  
  Contoh: `np.array([7, 2, 9, 10])` punya `shape (4,)`

- **2D** → seperti “tabel” (matriks), bentuknya `(baris, kolom)`  
  Contoh: `np.array([[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]])` punya `shape (2, 3)`

- **3D** → seperti “tumpukan matriks”, bentuknya `(layer, baris, kolom)`  
  Contoh: data gambar berwarna sering punya shape `(tinggi, lebar, channel)`

> Intinya: **jumlah angka di `shape` = jumlah dimensi (`ndim`)**.


In [179]:
arr1d = np.array([1,2,3]) # array satu dimensi

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]) # array dua dimensi

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                  [[7, 8, 9], [10, 11, 12]]]) # array tiga dimensi


print("Array satu dimensi: \n", arr1d)
print("Array dua dimensi: \n", arr2d)
print("Array tiga dimensi: \n", arr3d)

Array satu dimensi: 
 [1 2 3]
Array dua dimensi: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array tiga dimensi: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Membuat Array dengan Fungsi Bawaan NumPy (Factory Functions)

> Catatan: beberapa fungsi seperti `np.empty()` tidak mengisi nilai awal. Itu normal, bukan error.

### `np.empty(shape)`
Membuat array **tanpa inisialisasi nilai** (isinya bisa terlihat 'acak'). Cocok kalau kamu mau isi nilainya belakangan.

In [180]:
a = np.empty((3,2), dtype=int)
print(f"Array bebas\n {a}")

Array bebas
 [[1 2]
 [3 4]
 [5 6]]


### `np.zeros(shape)`
Membuat array berisi **0**. Ini paling sering dipakai buat inisialisasi placeholder.

In [181]:
# np.zeros
b = np.zeros((5))
print(f"Array 0 (nol) \n {b}")

Array 0 (nol) 
 [0. 0. 0. 0. 0.]


### `np.ones(shape)`
Membuat array berisi **1**. Berguna untuk baseline / mask sederhana.

In [182]:
# np.ones
c = np.ones((5,5))
print(f"Array 1 (satu) \n {c}")

Array 1 (satu) 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### `np.full(shape, value)`
Membuat array berisi nilai yang sama (misal semua 7).

In [183]:
# np.full
d = np.full((2,2), 7)
print(f"Array full 7 \n {d}")

Array full 7 
 [[7 7]
 [7 7]]


### `np.eye(n)`
Membuat **matriks identitas** (diagonal 1, sisanya 0).

In [184]:
# np.eyes
e = np.eye(3)
print(f"Array identitas \n {e}")

Array identitas 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### `np.linspace(start, stop, num)`
Membuat deret angka dari `start` sampai `stop` dengan **jumlah titik** `num` (jaraknya rata).

**Rumus:**
$$\text{step} = \frac{\text{stop} - \text{start}}{\text{num} - 1}$$

Setiap titik ke-$i$: $\text{value}_i = \text{start} + i \times \text{step}$, dengan $i = 0, 1, 2, ..., \text{num}-1$

In [210]:
# np.linspace
f = np.linspace(0, 10, 5) 
print(f"Array linspace \n {f}")

Array linspace 
 [ 0.   2.5  5.   7.5 10. ]


### `np.random.rand(...)` 
Membuat angka acak uniform [0, 1). Untuk data science, lebih rapi pakai `default_rng()` biar reproducible (lihat setelah ini).

In [186]:
# np.random array random dengan matrix (3 x 2)
g = np.random.rand(3, 2)        
print(f"Array random matrix (3 x 2) \n {g}")

Array random matrix (3 x 2) 
 [[0.80086546 0.26152134]
 [0.16245016 0.13997489]
 [0.31538313 0.3623825 ]]


### Random yang Reproducible (Best Practice untuk Data Science)

Kalau lagi eksperimen model/EDA, biasanya mau hasil random yang **konsisten** saat notebook dijalankan ulang.

Rekomendasi NumPy modern: pakai **Generator API** lewat `np.random.default_rng(seed)`.

In [187]:
# Best practice: Generator API (reproducible)
rng = np.random.default_rng(42)

print("Random uniform (0-1) shape (3,2):\n", rng.random((3, 2)))
print("\nRandom integers 0..9 (5 angka):\n", rng.integers(0, 10, size=5))
print("\nRandom normal mean=0 std=1 (5 angka):\n", rng.normal(0, 1, size=5))


Random uniform (0-1) shape (3,2):
 [[0.77395605 0.43887844]
 [0.85859792 0.69736803]
 [0.09417735 0.97562235]]

Random integers 0..9 (5 angka):
 [7 7 7 7 5]

Random normal mean=0 std=1 (5 angka):
 [-0.85304393  0.87939797  0.77779194  0.0660307   1.12724121]


### `np.arange(start, stop, step)`
Mirip `range()`, tapi hasilnya array NumPy. Cocok untuk bikin index numerik.

In [188]:
# np.arange
h = np.arange(0, 10, 2) # (x, y, z) 
print(f"Array arange \n {h}")

i = list(range(0, 10, 2)) # 
print(f"Array range \n {i}")

Array arange 
 [0 2 4 6 8]
Array range 
 [0, 2, 4, 6, 8]


### Menampilkan informasi tentang `N-Dimensional Array`

In [189]:
print(arr1d)
print(arr2d)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


***ndarray*** merupakan class array di Numpy, yang memiliki beberapa properti:

- `ndim`: Dimensi/Level dari array (1D, 2D or etc)
- `shape`: Ukuran dimensi dari array, keluaran berupa python tuple dan menampilkan axis (dimensi) suatu array.
- `dtype`: Tipe data elemen yang ada dalam array
- `itemsize`: Byte per elemen
- `size`: Jumlah semua elemen dalam array
- `nbytes`: Jumlah total byte yang digunakan oleh array (`size * itemsize`)

In [190]:
print("Dimensi Array 1D:", arr1d.ndim)
print("Ukuran Array 1D:", arr1d.shape)
print("Tipe Data Array 1D:", arr1d.dtype)
print("Itemsize Array 1D (bytes per elemen):", arr1d.itemsize)
print("Jumlah semua elemen: ", arr1d.size)
print("Total ukuran memori (bytes):", arr1d.nbytes)

Dimensi Array 1D: 1
Ukuran Array 1D: (3,)
Tipe Data Array 1D: int32
Itemsize Array 1D (bytes per elemen): 4
Jumlah semua elemen:  3
Total ukuran memori (bytes): 12


In [191]:
print("Dimensi Array 2D:", arr2d.ndim)
print("Ukuran Array 2D:", arr2d.shape)
print("Tipe Data Array 2D:", arr2d.dtype)
print("Itemsize Array 1D (bytes per elemen):", arr2d.itemsize)
print("Jumlah semua elemen: ", arr2d.size)
print("Total ukuran memori (bytes):", arr2d.nbytes)

Dimensi Array 2D: 2
Ukuran Array 2D: (3, 3)
Tipe Data Array 2D: int32
Itemsize Array 1D (bytes per elemen): 4
Jumlah semua elemen:  9
Total ukuran memori (bytes): 36


### `Array Slicing` dan `Array Indexing`



Numpy memberikan berbagai cara untuk mengambil elemen di arrays dengan indexing.

1. `Slicing`: Mirip dengan python lists, array numpy dapat di-slicing. Slicing array juga dapat multidimensional, kamu harus menspesifikasikan slice tiap dimensi arraynya.

2. `Integer array indexing`: Berbeda dengan slicing, pengindeksan array integer memungkinkan Anda membuat array sembarang dengan menggunakan data dari array lain.

3. `Boolean array indexing`: Boolean array indexing memungkinkan Anda memilih elemen sembarang dari array. Jenis pengindeksan ini sering digunakan untuk memilih elemen array yang memenuhi suatu kondisi. 

In [192]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Misalnya kita ingin mengambil elemen di baris pertama dan elemen kedua (ex: a adalah 2) maka kita bisa menspesifikasikan indexnya.

`a[0,1]` = maka mengambil baris index 0 (baris pertama) dan index 1 (kolom kedua)

**NOTE**: Index dimulai dari 0 dan dimulai dari dimensi X, Y, Z dan seterusnya. Contohnya dalam array 2 dimensi maka X = baris dan Y = kolom

## Konsep Indexing di Python

Misal kita punya list:

```python
list_ = [10, 20, 30, 40, 50, 60]
```

**Index positif** mulai dari kiri (0, 1, 2, ...), sedangkan **index negatif** mulai dari kanan (-1, -2, ...).

| Elemen | 10 | 20 | 30 | 40 | 50 | 60 |
|---:|---:|---:|---:|---:|---:|---:|
| Index (+) | 0 | 1 | 2 | 3 | 4 | 5 |
| Index (-) | -6 | -5 | -4 | -3 | -2 | -1 |

✅ Yang sering dipakai:
- `list_[0]` → elemen pertama  
- `list_[-1]` → elemen terakhir

In [193]:
i1 = a[0, 1]
print(i1)

2


Tidak hanya satu elemen, kita bisa mengambil sub-array atau elemen array yang lebih kecil dari keseluruhan array. Misalnya ingin mengambil array di dua baris pertama dan kolom 2 dan 3.

In [194]:
i2 = a[:2, 1:3] # :2 menandakan mengambil semua baris sampai baris kedua dan 1:3 menandakan mengambil kolom 1 dan 2 (sebelum 3)
print(i2)

[[2 3]
 [6 7]]


Kemudian, misalnya ingin mengambil semua baris dan kolom dengan step 2 (kolom index kelipatan 2)

In [195]:
i3 = a[::,::2] 
print(i3)

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [196]:
# Another example
print("Element index ke-1 arr1d\t\t:", arr1d[1])
print("Element index ke-1 hingga 2 arr1d\t:", arr1d[1:3])
print("Element baris ke-1 dan kolom ke-2\t:", arr2d[0:2, 0])

Element index ke-1 arr1d		: 2
Element index ke-1 hingga 2 arr1d	: [2 3]
Element baris ke-1 dan kolom ke-2	: [1 4]


**Reminder**: Untuk memahami bagaimana slicing index array berjalan, perlu diingat bagaimana slicing di python sendiri berjalan

Format Indexing Python:<br>
```A:B:C```

- `A`: A melambangkan start_index, angka pertama yang ingin diiterasikan
- `B`: B melambangkan end_index, target iterasi sampai iterasi ke-(B - 1) atau sebelum B
- `C`: C melambangkan filtering, dimana kita ingin mengambil data berdasarkan kelipatan apa?

Referensi: 
https://www.freecodecamp.org/news/slicing-and-indexing-in-python/

**Tidak hanya** menampilkan suatu data di array, menggunakan slicing juga dapat **mengubah elemen dalam array**.

In [197]:
c = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print("Sebelum modifikasi array\n", c)

c[0,0] = 100
print("Setelah modifikasi array\n", c)

Sebelum modifikasi array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Setelah modifikasi array
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


Dikarenakan array bersifat **data referensi**, maka kita bisa mengubah informasi elemen jika mengakses index yang berlokasi sama (meski berbeda indexnya)

In [198]:
b = a[:2, 1:3]

print(a[0, 1])

b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

2
77


#### View vs Copy

Saat slicing NumPy, kamu perlu sadar: **apakah hasilnya "nempel" ke array asal (view)** atau **salinan baru (copy)**?

- **Basic slicing** (`arr[2:6]`, `arr[:, 1:3]`) → biasanya menghasilkan **view**  
  Artinya: kalau kamu ubah hasil slicing, array asal **ikut berubah**.
- **Advanced indexing** (pakai list index atau boolean mask) → menghasilkan **copy**  
  Artinya: kamu ubah hasilnya, array asal **tidak ikut berubah**.

Kapan ini kepake di Data Science?
- Hemat memori (view) saat data besar
- Tapi kalau kamu mau aman (nggak mengubah data asli), pakai `.copy()`

Referensi resmi:
- Copies & views: https://numpy.org/doc/stable/user/basics.copies.html
- Indexing: https://numpy.org/doc/stable/user/basics.indexing.html


In [199]:
arr = np.arange(10)
print("arr:", arr)

# 1) Basic slicing -> view
view = arr[2:6]
print("\nview:", view)
print("view.base is arr?", view.base is arr)

# 2) Advanced indexing -> copy
copy_arr = arr[[2, 3, 4, 5]]
print("\ncopy_arr:", copy_arr)
print("copy_arr.base is None?", copy_arr.base is None)

# Coba ubah
view[0] = 999
copy_arr[0] = 777

print("\nSetelah diubah:")
print("arr:", arr, "  <-- berubah karena view")
print("view:", view)
print("copy_arr:", copy_arr, "  <-- arr tidak berubah karena ini copy")


arr: [0 1 2 3 4 5 6 7 8 9]

view: [2 3 4 5]
view.base is arr? True

copy_arr: [2 3 4 5]
copy_arr.base is None? True

Setelah diubah:
arr: [  0   1 999   3   4   5   6   7   8   9]   <-- berubah karena view
view: [999   3   4   5]
copy_arr: [777   3   4   5]   <-- arr tidak berubah karena ini copy


Berikutnya, kita eksplor nih bagaimana `integer array indexing`.

In [200]:
a = np.array([
    [1, 2], 
    [3, 4], 
    [5, 6]
])

# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


Berikut merupakan contoh bagaimana `boolean array indexing`.

In [201]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [202]:
# Kita juga bisa menggunakan indexing array ini untuk membuat array 1D yang mencakup
# semua elemen yang True dalam bool_idx
print(a[bool_idx])

# Atau bisa dilakukan dalam satu line statement
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


### Tipe Data (`Datatypes`)

Nah dalam numpy array sendiri juga terdapat jenis tipe data yang dapat digunakan. Dalam satu grid array, elemen memiliki tipe data yang sama dan menyediakan large set tipe data numeric yang dapat digunakan dalam array.

Numpy juga dapat **menebak tipe data apa yang digunakan** saat membuat array, tetapi kita juga bisa (optional) secara **spesifik memilih tipe data** yang diinginkan. 

In [203]:
x = np.array([1, 2])  # Numpy otomatis memilihkan tipe data
y = np.array([1.0, 2.0])  # Numpy otomatis memilihkan tipe data
z = np.array([1, 2], dtype=np.int64)  # Memilih tipe data sendiri

print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


Kamu bisa baca lebih lanjut mengenai tipe data yang ada dalam numpy di [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### `Statistical` Function

Nah, salah satu benefit numpy adalah built-in functionnya. Nah salah satunya untuk menghitung **statistik** seperti *mean, median atau standar deviasi* suatu array.

In [204]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Menghitung statistik
mean_value = np.mean(arr2d, axis=0)
median_value = np.median(arr2d)
std_deviation = np.std(arr2d)

print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)

Mean: [4. 5. 6.]
Median: 5.0
Standard Deviation: 2.581988897471611


Bukan sebatas itu, kamu bisa eksplor built-in function mengenai statistik di [documentation](https://numpy.org/doc/2.2/reference/routines.statistics.html)

### `Math` Function

Selain array, numpy bisa juga digunakan untuk keperluan **matematika** seperti:
- `amin`: mengembalikan nilai minimum dalam array
- `amax`: mengembalikan nilai maksimum dalam array
- `sum`: mengembalikan sum atau jumlah semua elemen di array
- `sqrt`: mengembalikan hasil square root elemen di array
- `sin`: function untuk mencari sinus trigonometri
- `cos`: function untuk mencari cosinus trigonometri
- `std`: mengembalikan standar deviasi suatu array
- `log`: mengembalikan hasil logaritam
- `exp`: mengembalikan hasil pangkat suatu array
- operator (+, -, *, /, etc)
dan lain-lainnya

In [206]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Min dan Max
print("\nMinimum dan Maximum")
print(f"Min: {np.amin(x)}")
print(f"Max: {np.amax(x)}")

# Sum (total semua elemen)
print("\nSum")
print(f"Total semua elemen x: {np.sum(x)}")
print(f"Sum per kolom: {np.sum(x, axis=0)}")
print(f"Sum per baris: {np.sum(x, axis=1)}")

# Elementwise square root
print("\nSquare Root")
print(np.sqrt(x))

# Trigonometri (sin, cos)
angles = np.array([0, np.pi/2, np.pi])
print("\nTrigonometri")
print(f"Angles: {angles}")
print(f"Sin: {np.sin(angles)}")
print(f"Cos: {np.cos(angles)}")

# Standard Deviation
print("\nStandard Deviation")
print(f"Std dari x: {np.std(x)}")

# Logaritma dan Eksponensial
print("\nLog dan Exp")
print(f"Log natural x: \n{np.log(x)}")
print(f"Exp x: \n{np.exp(x)}")

# Elementwise penjumlahan; sama2 menghasilkan array
print("Sum")
print(x + y)
print(np.add(x, y))

# Elementwise perbedaan; sama2 menghasilkan array
print("\nDifference")
print(x - y)
print(np.subtract(x, y))

# Elementwise product/perkalian; sama2 menghasilkan array
print("\nProduk")
print(x * y)
print(np.multiply(x, y))

# Elementwise division; sama2 menghasilkan array
print("\nDivision")
print(x / y)
print(np.divide(x, y))


Minimum dan Maximum
Min: 1.0
Max: 4.0

Sum
Total semua elemen x: 10.0
Sum per kolom: [4. 6.]
Sum per baris: [3. 7.]

Square Root
[[1.         1.41421356]
 [1.73205081 2.        ]]

Trigonometri
Angles: [0.         1.57079633 3.14159265]
Sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]

Standard Deviation
Std dari x: 1.118033988749895

Log dan Exp
Log natural x: 
[[0.         0.69314718]
 [1.09861229 1.38629436]]
Exp x: 
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
Sum
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]

Difference
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]

Produk
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]

Division
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Kamu juga bisa eksplor kumpulan math functions yang disediakan oleh numpy di [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

### `Arithmetic` Function

Selain itu, kamu juga dapat menggunakan built-in function untuk melakukan **fungsi aritmatika** seperti *transposisi, dot product* dan lainnya

In [207]:
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

# Operasi Transposisi
transposed_arr = arr1.T
transposed_arr = np.transpose(arr1)
print("Transposed Array arr1:\n", transposed_arr)

# Operasi dot product
dot_product = np.dot(arr1, arr2)
dot_product = arr1.dot(arr2)
print("Dot Product:\n", dot_product)

Transposed Array arr1:
 [[1 3]
 [2 4]]
Dot Product:
 [[19 22]
 [43 50]]


### `Reshaping` Array

**Reshape** adalah metode dalam NumPy yang digunakan untuk mengubah bentuk (shape/dimensi) dari sebuah array NumPy tanpa mengubah isi datanya.

In [208]:
# Membuat array 1D dengan 9 elemen menggunakan method arange
# 0, 1, 2, 3, 4, 5, 6, 7, 8

arr1d = np.arange(start=0, step=1, stop=9)
print("Array 1D:")  
print(arr1d)

# Mengubah array 1D menjadi matriks 3x3
arr2d_3x3 = arr1d.reshape(3, 3)
print("Matriks 3x3:")
print(arr2d_3x3)

# Mengubah array 1D menjadi vektor baris 1x9
arr2d_row = arr1d.reshape(1, 9)
print("Vektor Baris 1x9:")
print(arr2d_row)

# Mengubah array 1D menjadi vektor kolom 9x1
arr2d_col = arr1d.reshape(9, 1)
print("Vektor Kolom 9x1:")
print(arr2d_col)

Array 1D:
[0 1 2 3 4 5 6 7 8]
Matriks 3x3:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Vektor Baris 1x9:
[[0 1 2 3 4 5 6 7 8]]
Vektor Kolom 9x1:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [209]:
a = np.array([[1,2,3]])   # (1,3)
b = np.array([[4],[5],[6]])  # (3,1)

print(np.dot(a,b))
print(np.dot(b,a))


[[32]]
[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]


### Bonus 🎁

Berikut merupakan overview singkat mengenai topik penting yang perlu kamu ketahui mengenai numpy. Kalau mau lebih dalam lagi, kamu bisa cek [numpy reference](http://docs.scipy.org/doc/numpy/reference/).

### QnA 🙏

<img src="https://media.tenor.com/ayjJMkutts4AAAAm/sheep-minecraft.webp" alt="Health Points" width="200">