# **TUGAS NUMPY 2026** 🧮

---
**Nama: Naufal Fadhil Arkani**  
**NIM: 255150200111037**  

Notebook ini berisi penugasan **NumPy** sebagai latihan lanjutan setelah workshop.

### Aturan singkat
- Kerjakan mandiri.
- Gunakan **NumPy** sebagai alat utama.
- Untuk soal yang berkaitan dengan masking, broadcasting, dan reshaping, usahakan **tidak menggunakan loop** jika memang bisa diselesaikan dengan operasi NumPy.
- Tulis jawaban langsung di cell yang sudah disediakan.


## **📦 Import Library**

Jalankan cell berikut terlebih dahulu.


In [1]:
import numpy as np

# Seed supaya hasil random konsisten
rng = np.random.default_rng(42)


## **📌 Soal 1: Membuat Array & Membaca Informasinya**

Buatlah array NumPy bernama `scores` dengan isi nilai berikut:

`[78, 85, 90, 66, 74, 88, 92, 81]`

Lalu tampilkan:
1. Isi array
2. Jumlah dimensi
3. Shape
4. Banyak elemen
5. Tipe data

**Hint:** gunakan `np.array`, lalu cek `ndim`, `shape`, `size`, dan `dtype`.


In [5]:
# Tulis jawabanmu di sini
scores = np.array([78, 85, 90, 66, 74, 88, 92, 81])

print("Isi array: ", scores)
print("Jumlah dimensi: ", scores.ndim)
print("Shape: ", scores.shape)
print("Banyak elemen: ", scores.size)
print("Tipe data: ", scores.dtype)

Isi array:  [78 85 90 66 74 88 92 81]
Jumlah dimensi:  1
Shape:  (8,)
Banyak elemen:  8
Tipe data:  int64


## **📌 Soal 2: Factory Functions**

Gunakan fungsi bawaan NumPy untuk membuat:
1. Array `A` berukuran `3x4` yang seluruh elemennya `0`
2. Array `B` berukuran `2x3` yang seluruh elemennya `1`
3. Array `C` berukuran `3x3` yang seluruh elemennya `7`
4. Matriks identitas `D` berukuran `4x4`
5. Array `E` yang berisi 6 angka dari `0` sampai `1` dengan jarak sama rata

Tampilkan semua hasilnya.


In [8]:
# Tulis jawabanmu di sini
A = np.zeros((3, 4))
B = np.ones((2, 3))
C = np.full((3, 3), 7)
D = np.eye(4)
E = np.linspace(0, 1, 6)

print("Array A:\n", A)
print()
print("Array B:\n", B)
print()
print("Array C:\n", C)
print()
print("Matriks identitas D:\n", D)
print()
print("Array E:\n", E)

Array A:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array B:
 [[1. 1. 1.]
 [1. 1. 1.]]

Array C:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Matriks identitas D:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Array E:
 [0.  0.2 0.4 0.6 0.8 1. ]


## **📌 Soal 3: Indexing & Slicing**

Perhatikan array berikut:


In [9]:
arr = np.arange(1, 17).reshape(4, 4)
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Dari array tersebut, tampilkan:
1. Elemen pada baris ke-2 kolom ke-3
2. Seluruh baris pertama
3. Seluruh kolom terakhir
4. Subarray 2x2 di tengah
5. Array hasil membalik urutan kolom pada semua baris

**Catatan:** gunakan indexing/slicing NumPy.


In [16]:
# Tulis jawabanmu di sini
print(arr[1, 2])
print()
print(arr[0, :])
print()
print(arr[:, 3])
print()
print(arr[1:3, 1:3])
print()
print(arr[:, ::-1])


7

[1 2 3 4]

[ 4  8 12 16]

[[ 6  7]
 [10 11]]

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


## **📌 Soal 4: Boolean Masking & `np.where()`**

Diberikan array suhu berikut:


In [17]:
temps = np.array([29, 31, 35, 28, 33, 27, 30, 36, 32, 26])
print(temps)


[29 31 35 28 33 27 30 36 32 26]


Kerjakan hal berikut:
1. Ambil semua suhu yang **lebih dari 30**
2. Hitung berapa banyak suhu yang **lebih dari atau sama dengan 32**
3. Buat array label baru bernama `status` dengan aturan:
   - `"panas"` jika suhu > 32
   - `"normal"` jika suhu 29 s.d. 32
   - `"dingin"` jika suhu < 29

**Hint:** untuk poin (3), kamu bisa menggunakan `np.where()` bertingkat.


In [21]:
# Tulis jawabanmu di sini
over30 = temps[temps > 30]
print(over30)
print()

count_over32 = temps[temps >= 32].size
print(count_over32)
print()

status = np.where(temps > 32, "panas", np.where(temps >= 29, "normal", "dingin"))
print(status)

[31 35 33 36 32]

4

['normal' 'normal' 'panas' 'dingin' 'panas' 'dingin' 'normal' 'panas'
 'normal' 'dingin']


## **📌 Soal 5: View vs Copy**

Buat array berikut:


In [22]:
x = np.array([10, 20, 30, 40, 50, 60])
print(x)


[10 20 30 40 50 60]


Lalu lakukan:
1. Buat `view_part` dari elemen indeks 1 sampai 4 menggunakan slicing
2. Buat `copy_part` dari elemen indeks `[1, 2, 3, 4]` menggunakan advanced indexing
3. Ubah elemen pertama `view_part` menjadi `999`
4. Ubah elemen pertama `copy_part` menjadi `-100`
5. Tampilkan `x`, `view_part`, dan `copy_part`

Terakhir, tuliskan dengan singkat:
- mana yang menyebabkan array asli berubah?
- mana yang tidak?


In [25]:
# Tulis jawabanmu di sini
# Tambahkan penjelasan singkat dalam komentar juga.

view_part = x[1:5]
copy_part = x[[1, 2, 3, 4]]
view_part[0] = 999
copy_part[0] = -100

print("Array asli: ", x)
print("Array view_part: ", view_part)
print("Array copy_part: ", copy_part)

# Perubahan pada view_part mengubah isi dari array asli x, hal ini disebabkan array merupakan variabel bertipe data reference sehingga ketika dilakukan slicing variabel view_part akan menyalin referensi dari X yang mana membuat ketika view_part diubah maka x akan ikut berubah
# Perubahan pada copy_part tidak akan mengubah array asli x karena copy_part adalah array yang sepenuhnya baru yang hanya menyalin isi dari variabel x melalui advance indexing

Array asli:  [ 10 999  30  40  50  60]
Array view_part:  [999  30  40  50]
Array copy_part:  [-100   30   40   50]


## **📌 Soal 6: Statistik Dasar & Missing Value (`NaN`)**

Gunakan array berikut:


In [26]:
values = np.array([12, 15, np.nan, 18, 21, np.nan, 24, 30])
print(values)


[12. 15. nan 18. 21. nan 24. 30.]


Tampilkan:
1. Rata-rata biasa dengan `np.mean()`
2. Rata-rata yang mengabaikan `NaN` dengan `np.nanmean()`
3. Standar deviasi yang mengabaikan `NaN` dengan `np.nanstd()`
4. Nilai minimum dan maksimum yang mengabaikan `NaN`

Lalu jelaskan singkat kenapa hasil `np.mean()` bisa berbeda dari `np.nanmean()`.


In [28]:
# Tulis jawabanmu di sini
print("Rata-rata biasa: ", np.mean(values))
print("Rata-rata yang mengabaikan NaN: ", np.nanmean(values))
print("Standar deviasi yang mengabaikan NaN: ", np.nanstd(values))
print("Nilai minimum: ", np.nanmin(values))
print("Nilai maksimum: ", np.nanmax(values))

# Hasil np.mean() berbeda karena np.mean() akan tetap memasukkan dan menjumlahkan nilai NaN (np.nan), seluruh operasi yang melibatkan nilai NaN akan menghasilkan nan

Rata-rata biasa:  nan
Rata-rata yang mengabaikan NaN:  20.0
Standar deviasi yang mengabaikan NaN:  5.916079783099616
Nilai minimum:  12.0
Nilai maksimum:  30.0


## **📌 Soal 7: Broadcasting untuk Normalisasi**

Diberikan matriks fitur berikut:


In [29]:
X = np.array([
    [170, 65, 28],
    [165, 55, 24],
    [180, 75, 30],
    [175, 70, 29]
], dtype=float)

print(X)


[[170.  65.  28.]
 [165.  55.  24.]
 [180.  75.  30.]
 [175.  70.  29.]]


Anggap setiap kolom merepresentasikan fitur yang berbeda.  
Lakukan normalisasi z-score sederhana dengan rumus:

$$
Z = \frac{X - \text{mean kolom}}{\text{std kolom}}
$$

Tampilkan:
1. Mean per kolom
2. Std per kolom
3. Hasil normalisasi `Z`

**Hint:** gunakan `axis=0` dan manfaatkan broadcasting NumPy.


In [30]:
# Tulis jawabanmu di sini
rata2 = np.mean(X, axis=0)
std = np.std(X, axis=0)
Z = (X - rata2) / std

print("Mean per kolom: ", rata2)
print("Std per kolom: ", std)
print("Hasil normalisasi Z: \n", Z)

Mean per kolom:  [172.5   66.25  27.75]
Std per kolom:  [5.59016994 7.39509973 2.27760839]
Hasil normalisasi Z: 
 [[-0.4472136  -0.16903085  0.10976426]
 [-1.34164079 -1.52127766 -1.6464639 ]
 [ 1.34164079  1.18321596  0.98787834]
 [ 0.4472136   0.50709255  0.5488213 ]]


## **📌 Soal 8: Reshape & Mini Challenge**

Gunakan array 1 dimensi berikut:


In [43]:
z = np.arange(1, 25)
print(z)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


Kerjakan hal berikut:
1. Ubah `z` menjadi matriks berukuran `6x4`
2. Ubah hasilnya menjadi bentuk `3x2x4`
3. Ambil kembali seluruh data tersebut menjadi array 1 dimensi
4. Bonus: buat array window 4 elemen yang bergeser dari `z`, sehingga bentuk akhirnya menjadi:

`[[1,2,3,4], [2,3,4,5], ..., [21,22,23,24]]`

**Hint bonus:** boleh gunakan loop **atau** `sliding_window_view` jika kamu sudah tahu.


In [45]:
# Tulis jawabanmu di sini
z = z.reshape(6, 4)
print(z)
print()

z = z.reshape(3, 2, 4)
print(z)
print()

z = z.reshape(24)
print(z)
print()

z = np.array([z[i:i+4] for i in range(21)])
print(z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]
 [13 14 15 16]
 [14 15 16 17]
 [15 16 17 18]
 [16 17 18 19]
 [17 18 19 20]
 [18 19 20 21]
 [19 20 21 22]
 [20 21 22 23]
 [21 22 23 24]]


# **🎯 Penutup**

Kalau kamu sudah menyelesaikan semua soal:
- cek lagi hasil outputmu,
- pastikan bentuk array dan logikanya sesuai,
- lalu simpan notebook ini sebelum dikumpulkan.

Semangat! 🚀
